# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"
#ZSH_THEME=""

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Pure prompt theme
fpath+=("/home/pakkapon/.zsh/pure")
autoload -U promptinit; promptinit

PURE_CMD_MAX_EXEC_TIME=10

zstyle ':prompt:pure:path' color yellow
zstyle ':prompt:pure:prompt:*' color cyan
zstyle ':prompt:pure:user' color green
zstyle ':prompt:pure:virtualenv' color green
zstyle ':prompt:pure:host' color cyan
zstyle ':prompt:pure:user:root' color red
zstyle ':prompt:pure:execution_time' color red
zstyle :prompt:pure:git:stash show yes

prompt pure

# fzf configuration
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# classic run command

run() {
    # Usage:
    #   run @v9g0 python hello.py

    TARGET="$1"
    shift
    CMD="$*"

    # Remove leading @
    SPEC="${TARGET#@}"

    # Parse host and GPU
    HOST="${SPEC%%g*}"      # v9
    GPU="${SPEC##*g}"       # 0

    SESSION="run"
    WINDOW="$SPEC"
    CWD="$(pwd)"

    # Create tmux session if it doesn't exist
    if ! tmux has-session -t "$SESSION" 2>/dev/null; then
        tmux new-session -d -s "$SESSION"
    fi

    # Create new window
    tmux new-window -t "$SESSION" -n "$WINDOW"

    # SSH, run command, then keep shell alive
    tmux send-keys -t "$SESSION:$WINDOW" \
        "ssh -t $HOST 'cd \"$CWD\" && CUDA_VISIBLE_DEVICES=$GPU $CMD; exec \$SHELL'" C-m

    # Attach to tmux
    tmux attach -t "$SESSION"
}

# launch command for light
lm() {
    # Usage:
    #   lm @v5g0 python fit_single_light_x_axis_test.py

    local TARGET="$1"
    shift
    local CMD="$*"

    local SPEC="${TARGET#@}"
    local HOST="${SPEC%%g*}"      # v5
    local GPU="${SPEC##*g}"       # 0

    local SESSION="light-mesh"
    local WINDOW="$SPEC"
    local CWD="$(pwd)"

    # Create session if needed
    if ! tmux has-session -t "$SESSION" 2>/dev/null; then
        tmux new-session -d -s "$SESSION"
    fi

    # Create window or split pane
    if tmux list-windows -t "$SESSION" | grep -q "^.*: $WINDOW"; then
        # Horizontal split (left/right)
        tmux split-window -h -t "$SESSION:$WINDOW"
    else
        tmux new-window -t "$SESSION" -n "$WINDOW"
    fi

    # Equalize panes
    tmux select-layout -t "$SESSION:$WINDOW" tiled

    # Target newest pane
    local PANE="$(tmux list-panes -t "$SESSION:$WINDOW" -F '#{pane_id}' | tail -n 1)"

    local REMOTE_CMD="/pure/f1/project/light-mesh/bin/run ${CMD}"

    # Run command and keep shell alive
    tmux send-keys -t "$PANE" \
        "ssh -t $HOST 'cd \"$CWD\" && CUDA_VISIBLE_DEVICES=$GPU $REMOTE_CMD; exec \$SHELL'" C-m

    # Attach
    tmux attach -t "$SESSION"
}




alias s="singularity run --nv --env SSH_CONNECTION=\$SSH_CONNECTION --bind /tmp:/tmp --bind /pure/f1/conda/:/conda_envs --bind /pure:/pure --bind /ist:/ist --bind /ist-nas:/ist-nas /pure/f1/singularity/ubuntu.sif"
alias b="source ~/base/bin/activate"
alias g="/home/pakkapon/base/bin/python /home/pakkapon/dotfiles-mothership/scripts/lsgpu.py"
alias gs="/home/pakkapon/base/bin/python /home/pakkapon/dotfiles-mothership/scripts/lsgpu.py --spec"
alias gw="watch -n 120 /home/pakkapon/base/bin/python /home/pakkapon/dotfiles-mothership/scripts/lsgpu.py"
